//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquorWine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquorTb
    {
        public Nullable<int> ShopId { get; set; }
        public int LiquorId { get; set; }
        public string LiquorName { get; set; }
        public string LiquorQuantity { get; set; }
        public string LiquorImage { get; set; }
        public string LiquorAmount { get; set; }
    
        public virtual ShopTb ShopTb { get; set; }
    }
}
