//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquorWine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopTb
    {
        public ShopTb()
        {
            this.LiquorTbs = new HashSet<LiquorTb>();
        }
    
        public int ShopId { get; set; }
        public string ShopName { get; set; }
        public string OwnerName { get; set; }
        public string ShopPhone { get; set; }
        public string ShopEmail { get; set; }
        public string ShopAddress { get; set; }
        public string Gender { get; set; }
        public string Language { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<LiquorTb> LiquorTbs { get; set; }
    }
}
